accelerator: gpu
batch_size: 26
checkpoint: checkpoint
gradient_clip_val: 1.0
lr: 3.0e-05
max_epochs: 25
max_len: 512
num_gpus: 1
num_workers: 8
test_file: /home/alpaco/hw/KoBART-summarization/data/test.tsv
train_file: /home/alpaco/hw/KoBART-summarization/data/train.tsv
