accelerator: gpu
batch_size: 26
checkpoint: checkpoint
gradient_clip_val: 1.0
lr: 0.0005
max_epochs: 201
max_len: 512
num_gpus: 1
num_workers: 64
test_file: /home/alpaco/hw/KoBART-summarization/data/test.tsv
train_file: /home/alpaco/hw/KoBART-summarization/data/train.tsv
