resume_from_checkpoint_path: '/home/alpaco/final_Project/donut/result/train_cord/test01/'
result_path: '/home/alpaco/final_Project/donut/result/'
pretrained_model_name_or_path: 'naver-clova-ix/donut-base-finetuned-cord-v2'
dataset_name_or_paths: 
  - '/home/alpaco/final_Project/donut/synthdog/outputs/KoreanData'
sort_json_key: False
train_batch_sizes: 
  - 3
val_batch_sizes: 
  - 1
input_size: 
  - 1280
  - 960
max_length: 768
align_long_axis: False
num_nodes: 1
seed: 2022
lr: 3e-05
warmup_steps: 15000
num_training_samples_per_epoch: 800
max_epochs: 1300
max_steps: -1
num_workers: 8
val_check_interval: 1.0
check_val_every_n_epoch: 5
gradient_clip_val: 1.0
verbose: True
exp_name: 'train_cord'
exp_version: 'test01'